# Used for maze game.

import random

# List of encouraging messages
messages = [
    "You feel confident that the treasure draws near...",
    "A sense of destiny fills your heart as you venture deeper...",
    "You hear a faint, melodic chime. The treasure must be close.",
    "You catch a whiff of ancient, enchanted gold...",
    "Your steps become lighter, the treasure's aura guiding you...",
    "The walls seem to whisper secrets of the treasure...",
    "You sense an ancient magic growing stronger...",
    "You notice the air becoming warmer, the treasure's glow perhaps?",
    "The echoes of the labyrinth seem more cheerful...",
    "You find footprints leading forward, someone else sought the treasure too.",
    "Your heart races with anticipation, the treasure must be near...",
    "You feel an ethereal pull guiding you onward...",
    "A subtle shimmer on the walls hints at the treasure's proximity...",
    "You sense a protective presence guiding you...",
    "You find a discarded map with an X marked not far from here...",
    "Your instincts tell you that the treasure is just around the corner...",
    "You feel an inexplicable connection to this place, like you belong here...",
    "A sudden breeze brings the scent of old, polished coins...",
    "The air hums with a magical resonance, the treasure's song...",
    "You feel a surge of bravery as you press forward...",
    "You realize you may have left the stove on at home.",
    "You feel a sudden clarity of mind, the treasure guides you...",
    "A quiet confidence fills you, the treasure is not far...",
    "You hear the faint clinking of coins, a sure sign you're close...",
    "You realize you forgot to feed your pet rock.",
    "You hear strange scuffling sounds ahead. Probably nothing...",
    "You feel an ancient spirit guiding you towards the treasure...",
    "You hear a scratching on the walls from the other side...",
    "You smell mildew and brine, the dungeon fumes spin your head for a moment...",
    "You find a trail of glittering dust leading forward...",
    "You realize this moment was destined, the treasure is near...",
    "You find an old note: 'Beware of the chicken.'",
    "The walls seem to glow with a faint light, guiding you...",
    "You feel a serene calm, the treasure's magic envelops you...",
    "You hear a triumphant fanfare in your mind, the treasure is close...",
    "You sense a protective force around you as you near the treasure...",
    "You hear a distant melody, as if calling you to the treasure...",
    "The labyrinth feels less intimidating, the treasure's near...",
    "The path ahead seems clearer, almost as if lit by the treasure's glow...",
    "You find a sign: 'Don't feed the trolls.'",
    "You hear a joyful whisper in the air, a sign of the treasure's proximity...",
    "You catch a glimpse of something shiny ahead...",
    "Your heart beats in sync with the treasure's aura...",
    "You hear the faint sound of laughter echoing through the halls...",
    "You find a mysterious rune carved into the wall...",
    "You hear the wind whisper your name...",
    "You notice an old, worn-out boot lying on the ground.",
    "You hear a soft growl, but can't tell where it's coming from...",
    "You feel an eerie chill, as if watched by unseen eyes...",
    "You find a note: 'Turn back while you can.'",
    "You feel the ground beneath you hum with ancient power...",
    "You hear the distant sound of a harp being played...",
    "You notice the walls seem to pulse with energy...",
    "You find a small, enchanted trinket lying on the floor."
]

# List of character quotes
quotes = [
    "The moon told me secrets the sun can't understand.",
    "If you dance with shadows, make sure they lead.",
    "I've seen the end of infinity; it loops back to a beginning.",
    "The clouds are whispering your name.",
    "Your left shoe knows more about the universe than your right.",
    "Stars are just holes in the sky's fabric.",
    "What if mirrors are portals to alternate realities?",
    "The trees know where the treasure is buried.",
    "Time tastes like oranges.",
    "The universe hiccups when you sneeze.",
    "Dreams are just another form of reality.",
    "I've met a talking fish who sang opera.",
    "Beware the whispers of the forgotten socks.",
    "Rain is the sky crying because it misses the sea.",
    "The wind carries secrets from distant lands.",
    "Reality is just a canvas for our dreams.",
    "Your shadow is plotting something.",
    "The stars are just fireflies stuck in the sky.",
    "I've seen a rainbow with too many colors.",
    "The grass sings when no one is listening.",
    "Each leaf is a story waiting to be told.",
    "I've danced with the spirits of the forest.",
    "The sun is just a giant lemon drop.",
    "Night is the universe's way of telling you to rest.",
    "I've heard the mountains snore.",
    "What if the stars are just giant disco balls?",
    "The moon is the sun's reflective twin.",
    "I once saw a river flow backwards.",
    "Dreams are like whispers from another world.",
    "The trees have eyes and ears everywhere.",
    "I've seen a butterfly with wings of gold.",
    "The ocean's waves are just its way of saying hello.",
    "Each grain of sand has a story to tell.",
    "The sun sings, but we can't hear it.",
    "I've tasted the wind; it was salty.",
    "Reality is a song we all hum together.",
    "Your reflection has a mind of its own.",
    "I've seen shadows dance in the moonlight.",
    "The stars are just glitter spilled by the gods.",
    "I once found a pebble that told me its life story.",
    "The clouds are just fluffy dreams.",
    "I've met a cat who spoke in riddles.",
    "The mountains have secrets buried deep within.",
    "I've seen a sunset that lasted forever.",
    "The night is a blanket woven from dreams.",
    "Each star is a wish waiting to be made.",
    "I've heard the forest sing in harmony.",
    "The sky is just a giant canvas for the clouds.",
    "The wind has its own language.",
    "I've seen a flower that bloomed in the moonlight.",
    "The sun and moon are eternal dance partners.",
    "I've met a bird who knew the meaning of life.",
    "The stars are just memories from ancient times.",
    "The ocean whispers secrets to those who listen.",
    "I've seen a rainbow made of sound.",
    "Dreams are the footprints of our souls.",
    "The trees sway to the rhythm of the earth.",
    "The mountains echo with the voices of the past.",
    "I've seen a river that flowed with colors.",
    "I've heard the sun laugh.",
    "The moon has a twin on the other side of the world.",
    "The wind dances through the leaves.",
    "I've seen a butterfly with transparent wings.",
    "The clouds are the sky's diary entries.",
    "The ocean's waves are its lullabies.",
    "I've met a fox who told me jokes.",
    "The stars are just the universe's freckles.",
    "The night sky is a storybook waiting to be read.",
    "The sun sets because it's tired.",
    "I've seen a tree that glowed in the dark.",
    "The mountains are the earth's shoulders.",
    "The stars are just dreams of distant worlds.",
    "I've heard the rain sing a lullaby.",
    "The sky is a giant mirror reflecting our dreams.",
    "The ocean's waves are its sighs.",
    "I've met a wolf who gave me advice.",
    "The stars are just the universe's tears.",
    "The night sky is a canvas for the stars.",
    "The sun rises to chase away the night.",
    "I've seen a flower that whispered secrets.",
    "The mountains are the earth's wisdom.",
    "The stars are just dreams of the night.",
    "I've heard the wind tell stories.",
    "The sky is a painting that changes every day.",
    "The ocean's waves are its emotions.",
    "I've met a rabbit who knew the future.",
    "The stars are just the universe's thoughts.",
    "The night sky is a symphony of lights.",
    "The sun sets to rest its eyes.",
    "I've seen a tree that danced in the wind.",
    "The mountains are the earth's memories.",
    "The stars are just dreams waiting to be dreamt.",
    "I've heard the rain laugh.",
    "The sky is a dreamer's paradise.",
    "The ocean's waves are its heartbeat.",
    "I've met a deer who spoke in poetry.",
    "The stars are just the universe's whispers."
]

# Dictionary of items with score increases
items = {
    "Golden Apple": 15,
    "Silver Coin": 10,
    "Ancient Scroll": 20,
    "Mystic Gem": 25,
    "Crystal Feather": 18,
    "Enchanted Sword": 30,
    "Magic Wand": 22,
    "Healing Potion": 12,
    "Dragon Scale": 28,
    "Phoenix Feather": 25,
    "Elven Bow": 20,
    "Dwarven Hammer": 15,
    "Wizard's Hat": 18,
    "Sorcerer's Stone": 35,
    "Knight's Shield": 20,
    "Fairy Dust": 14,
    "Mermaid's Tear": 25,
    "Goblin's Ear": 10,
    "Vampire Fang": 18,
    "Werewolf Claw": 20,
    "Unicorn Horn": 30,
    "Griffin Talon": 22,
    "Basilisk Eye": 28,
    "Centaur Hoof": 15,
    "Giant's Tooth": 25,
    "Minotaur's Horn": 30,
    "Sphinx's Riddle": 20,
    "Oracle's Prophecy": 35,
    "Gnome's Cap": 12,
    "Troll's Club": 18,
    "Nymph's Blossom": 22,
    "Sprite's Wing": 15,
    "Djinn's Lamp": 28,
    "Cyclops' Eye": 25,
    "Harpy's Feather": 18,
    "Hydra's Head": 35,
    "Chimera's Tail": 30,
    "Dryad's Leaf": 12,
    "Pegasus Feather": 22,
    "Satyr's Flute": 20,
    "Kraken's Tentacle": 28,
    "Medusa's Lock": 25,
    "Phoenix Ashes": 30,
    "Ghostly Shroud": 18,
    "Witch's Broom": 20,
    "Ghoul's Bone": 15,
    "Specter's Cloak": 25,
    "Demon's Horn": 35,
    "Angel's Halo": 40
}

def get_random_message():
    if not messages:
        raise ValueError("No messages left")
    return messages.pop(random.randint(0, len(messages) - 1))

def get_random_quote():
    if not quotes:
        raise ValueError("No quotes left")
    return quotes.pop(random.randint(0, len(quotes) - 1))

def get_random_item():
    if not items:
        raise ValueError("No items left")
    item = random.choice(list(items.items()))
    del items[item[0]]
    return item
